name: Compile with nvfortran

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to NGC Docker Registry (nvcr.io)
        run: |
          echo "${{ secrets.NGC_API_KEY }}" | docker login nvcr.io -u '$oauthtoken' --password-stdin

      - name: Pull NVHPC Docker Image
        run: docker pull nvcr.io/nvidia/nvhpc:24.3-devel-cuda12.3-ubuntu22.04
        
      - name: Make build script executable
        run: chmod +x ./multi/local.sh

      - name: Run build script
        run: ./multi/local.sh
